dist: trusty
sudo: false
language: python
env:
- TOXENV=flake8
- TOXENV=isort
cache: pip
matrix:
  fast_finish: true
  include:
  - python: 3.6
    env: TOXENV=py36-1.11-drf3.5
  - python: 3.6
    env: TOXENV=py36-1.11-drf3.6
  - python: 3.6
    env: TOXENV=py36-2.1-drf3.7
  - python: 3.6
    env: TOXENV=py36-2.1-drf3.8
  - python: 3.6
    env: TOXENV=py36-2.1-drf3.9
  - python: 3.7
    dist: xenial
    sudo: true
    env: TOXENV=py37-2.1-drf3.7
  - python: 3.7
    dist: xenial
    sudo: true
    env: TOXENV=py37-2.1-drf3.8
  - python: 3.7
    dist: xenial
    sudo: true
    env: TOXENV=py37-2.1-drf3.9
  - python: 3.7
    dist: xenial
    sudo: true
    env: TOXENV=py37-2.1-drf3.10
install:
- pip install tox coveralls
script:
- tox
after_success:
- if [ -f .coverage ]; then coveralls; fi
